insecure_suites.go

Example sentence: "This cipher uses RC4 which has insecure biases in its output".

Grammar: "use RC4" -> "uses RC4"

---

all_suites.go
insecure_suites.go
static/about.html
templates/index.html

I used HTTPS Everywhere's rewriter tool to fix up URLs wherever possible:
https://github.com/EFForg/https-everywhere/blob/master/rewriter/rewriter.js
I was mainly targetting the HTML. The comment changes are probably overzealous,
but the tool caught them, and might as well, right?

Rewrite HTTP URLs to HTTPS.

---

gzip/LICENSE
gzip/README.md
gzip/gzip.go
gzip/gzip_test.go
gzip/header.go
gzip/reswriter.go
gzip/utils_test.go
howsmyssl.go

The homegrown gzip handler does not set the Content-Length correctly. Use the one from PuerkitoBio/ghost but copied and slightly edited to avoid the dependencies on everything else in ghost (e.g. redis). It turns us over to using `Transfer-Encoding: chunked`, instead.

correctly gzip static files

---

Dockerfile

No longer necessary on a modern Go.

remove GOMAXPROCS from Dockerfile

---

.travis.yml

Probably unnecessary, but just in case. Also, set GOOS just for completion even though it will certainly never be different.

add GOARCH to ensure we always get 64-bits

---

travis_docker_push.sh

Hey @jmhodges,
I would suggest to check for a folder underneath `$HOME/google-cloud-sdk` because this folder will be created by Travis CI under the hood when specifying it in the `cache.directories:` section of your .travis.yml file. Hence, `gcloud` won't be installed in this case.
Also, ensure to run at least 2 builds before seeing the cache in use: 1 build to populate the cache, 1 build to use it.
You can check the status of the cache in your build by searching the following phrases in the log and expanding them:
- `Setting up build cache`
- `store build cache`

Check for a folder underneath google-cloud-sdk folder

---

travis_docker_push.sh

Includes the git short sha to make it easier to know where a tag came from and put the TRAVIS_BUILD_NUMBER first since it gives us an ordering that is pretty accurately simulates the order they were in.

include short git sha in docker tag

---

Dockerfile
howsmyssl.go

Instead requiring the admin server to be local-only, allow to be exposed to the network. We drop the adminPort flag and gain an adminAddr flag.

allow admin server to be exposed to network

---

.travis.yml

This ensures that we use our vendored dependencies.

avoid Travis's go get by taking over install

---

allow.go
allow_test.go

Moving this len down let us count the domains even when we're not safelisting any domains at all.
Also, make the empty origin allower test reflect what we really wanted to test.

count domains even when the domain map is empty

---

allow.go
allow_test.go
config/development_origins.json
howsmyssl.go

This changes the config file's contents from the domains to allow to the ones to block. This makes it possible to do our abuse prevention without maintaining a persistent rate limit count.
Fixes #103

make origin config file specify domains to block

---

Dockerfile

Makes it easier to use with lekube

use ingress-style file paths for prod TLS keypair

---

travis_docker_push.sh

docker tag recently lost the -f param and we don't really need these so
just delete the whole thing

remove some unneeded docker tags

---

travis_docker_push.sh

With some help from another user in #google-containers in the Kubernetes slack,
we found this "legacy" option that apparently does not have a new solution. See
comment inside.

fix deploy tooling that Google broke

---

all_suites.go
insecure_suites.go

Previously, these were marked as insecure because they were unknown. But
they were asked for, so here they are.
The serendipity of the ticket they were asked for being 56 and all of
these being 56-bit cipher suites is nice.
Fixes #56

add a few more insecure cipher suites

---

travis_docker_push.sh

It was quickly deprecated and then removed.

remove email flag from docker push

---

travis_docker_push.sh

We now have a way to use kubectl patch without having to use the
client certificate. And we get roles working correctly, too.
Solved in kubernetes/kubernetes#30617

remove client certificate use in gcloud login

---

travis_docker_push.sh

fix GKE deploy again
gcloud no longer has the `beta auth` commands, so we have to do the work
ourselves. The deal is this:
When running in CI or other systems on Google Cloud machines with a
restricted Google account associated (like how Travis CI is configured),
you have to use `gcloud auth activate-service-account` before calling
`gcloud container clusters get-credentials`, but then have to override
that authentication by setting GOOGLE_APPLICATION_CREDENTIALS before
calling `kubectl`.
See https://github.com/kubernetes/kubernetes/issues/30617

fix GKE deploy again

---

all_suites.go

It's currently unnamed in the draft, so we call it "TLS_GREASE_IS_THE_WORD" for
now. See <https://tools.ietf.org/html/draft-davidben-tls-grease-01>.
Fixes #138

add Chrome GREASE cipher suite

---

all_suites.go

Adds all ciphersuites listed in
<https://tools.ietf.org/html/draft-davidben-tls-grease-01#section-5>.
Updates #138.

add all of the GREASE ciphersuites

---

travis_docker_push.sh

If a gcloud download and unpack failed midway, it might leave a directory with a
few files, but not all that we need. We could probably do with a manifest of
some kind, but this is patch that checks for the gcloud binary fixes the current
problem.

work harder to detect busted gcloud dirs

---

allow.go

This mimics how our HTTP handlers do it.

use 0.0.0.0 in Allower for busted IPs

---

Dockerfile
howsmyssl.go

Use `http.Server.Shutdown` and edit the Dockerfile so that kubernetes can send
SIGTERMs to the process successfully.

use Go 1.8's graceful HTTP server shutdown

---

howsmyssl.go

The `Done` methods might never be called if we panic.
An argument could be made that that is desirable so that kubernetes can tell us
when things are shutting down ungracefully, but I think that's unlikely to
happen and prefer all code using `WaitGroup`s to work the same so no one reading
this learns the wrong lessons

use defer when shutting down to avoid panics

---

client_info.go
insecure_suites.go
tls_test.go

Sweet32 ciphersuites should only be allowed as fallbacks now.

disallow Sweet32 ciphersuites out of order

---

allow.go
client_info.go
conn.go
howsmyssl.go
stat_writer.go
tls_test.go

Mostly renames of unexporting funcs and structs which isn't really a concern in a binary, but makes various linters get quieter. Also, an unnecessary json tag is removed.

some linter fixes

---

howsmyssl.go

Most domains don't check for the error or status code, so we have to get their attention.

include busted tls_version in block error

---

all_suites.go
client_info.go
tls18/handshake_client.go
tls_test.go

Things like renegotiation and GREASE should be allowed to be configured after
the Sweet32 cipher suites.

allow meta cipher suites to come after Sweet32 suites

---

client_info.go
conn.go
howsmyssl.go
reloader.go
tls110/common.go
tls110/conn.go
tls110/handshake_client.go
tls110/handshake_server.go
tls_test.go

This patches the tls110 package to include the vulnerability detection that we
have in tls18 already and uses tls110 instead of tls18 in howsmyssl.

patch tls110 with vuln detection and use it

---

client_info.go
tls110/common.go
tls110/conn.go
tls110/handshake_messages.go

Recent versions of the TLS 1.3 draft use a TLS extension called
supported_versions to announce the versions supported by the client. And
TLS 1.3 clients that support different drafts of the TLS 1.3 specs send
down different versions with the spec draft number bitmasked in.
This patch adds support for all of that behavior.
Fixes #201.

support TLS 1.3 supported_versions extension

---

client_info.go

This adds more TLS 1.3 versions that could show up in its
supported_versions extensions. Might still need more, but we're at draft
26 and we're doing about 1.5 versions a month right now. That rate of
versioning might accelerate as it gets closer to done

predict a few more TLS 1.3 drafts will happen

---

howsmyssl.go
index_test.go

Modern browsers won't run the JavaScript returned in the callback unless we
correct the Content-Type to application/javascript.
This patch fixes the problem and makes it possible to test the API inside our
tests with some slightly wild httptest hacks.

return correct jsonp Content-Type

---

howsmyssl.go
index_test.go

Turns out, when you do a <script src="yadda?callback=parseTLSThing">, the script
won't run if a 4xx error code is returned. So, in order for folks to show errors
to their users, and not just quietly log in their console, we have to return 200
OK even on blocked domains.
To be clear, normal AJAX requests would work, but people do that script tag
thing to be JSONP-y.
This patch also includes some new tests (and, along the way, a refactoring of
the current ones).

return 200 for blocked JSONP requests

---

howsmyssl.go
index_test.go

TooManyRequests implies to people that there will be strict API rate limits
instead of just needing to purchase a subscription which only has overage
charges.

use BadRequest instead of TooManyRequests

---

howsmyssl.go

The tls_version in disallowedOriginBody now no longer passes some sites that
were checking only `tls_version.split(' ')[1] < 1.2`.

reformat disallowedOriginBody

---

allow.go
allow_test.go

Some urls (I believe, in Referrers) were not being downcased by browsers before
being sent to howsmyssl.com. So, adjust that.

downcase urls for correct logging

---

gzip/header.go

Fix function comments following [Effective Go Guidelines](https://golang.org/doc/effective_go.html#commentary)

Fix function comments based on best practices from Effective Go

---

.github/workflows/update_dev_certs.yml

Our dev certs keep needing refreshing, but I'd rather not do it by hand. And I'd
rather not have to generate RSA keys on every test run. So, let's automate this.

add Github Action refresh our dev certs

---

.travis.yml

This reverts commit dab6fa60824119b2124f0b27b97cd8f4d39b62c1.
Got too hasty with #268. We still need Travis for the deploy code.

Revert "delete Travis CI config (#268)"

---

.github/workflows/go.yml
.github/workflows/update_dev_certs.yml

It turns out the actions/setup-go module does support using plain
version files for their go-version-file!
Since the Go version in `go.mod` is too imprecise (and isn't updated by
dependabot, anyway) for our purposes, let's use the plain version file
we've had around for a while.

use go-version-file with our version file

---

.github/workflows/go.yml

Running `go test ./...` no longer runs all the vendored library tests,
and whatever caching the install step was doing is now handled by Go's
module system internally. So, we can just do the test run.

remove install step from build

---

.github/workflows/build_and_deploy.yml
.github/workflows/deploy.yml
.github/workflows/go.yml

The deploy.yml workflow was being called twice on every merge to master.
Solve this without deploying on pull requests with a new workflow that
calls go.yml and deploy.yml on pushes to master and the test deploy
branches.

dedupe deploy by making new workflow

---

.github/workflows/build_and_deploy.yml
.github/workflows/go.yml

Previous config would have the go.yml workflow running twice on
test-deploy-* branches because go.yml looked to be run on `test-*`
branches and build_and_deploy.yml looked to be run on `test-docker-*`
branches.
Give up on using the built-in pattern matching and apply our own with
`if:`.

de-dupe Go calls on test- branches

---

.github/workflows/deploy.yml

Use GitHub Actions to deploy to Google Kubernetes Engine on merges to
master.
Uses OIDC to authenticate to GKE. Set up is done in private code.

continuously deploy with GitHub Actions

---

howsmyssl.go

In response to #25, we added this hack to strip the port of the Host
header before passing it to our virtual host redirecting ServeMux. I
also filed https://github.com/golang/go/issues/10463 and that was fixed
in 2017 and released soon after.
So, since we're on a modern version of Go, this code is redundant and
can be removed.

remove port stripping hack from our handlers

---

howsmyssl.go

The pattern time.Now().Sub has been replaced with time.Since for a long
while now.

use modern time.Since

---

howsmyssl.go

Now that we don't rely on hijack, we can use the statWriter to write our
metrics.
This probably would be better a deeper integration of our tracing work,
but this at least makes the metrics consistent.
Updates #530

use statWriter in ClientInfo handler

---

index_test.go
tls_test.go

This just removes some repeated type names that are no longer required
in modern Go.

run gofmt -w -s

---

.github/dependabot.yml

allow 15 dependabot PRs for Go deps

---

allow.go
gzip/utils_test.go
index_test.go
tls110/tls.go
tls_test.go

ioutil.ReadAll and ioutil.ReadFile have been deprecated for a few years
now. Fix them up.
Along the way, remove an unused test helper.

remove deprecated io calls

---

go.mod
index_test.go
vendor/github.com/google/go-cmp/LICENSE
vendor/github.com/google/go-cmp/cmp/compare.go
vendor/github.com/google/go-cmp/cmp/export.go
vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
vendor/github.com/google/go-cmp/cmp/internal/function/func.go
vendor/github.com/google/go-cmp/cmp/internal/value/name.go
vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
vendor/github.com/google/go-cmp/cmp/options.go
vendor/github.com/google/go-cmp/cmp/path.go
vendor/github.com/google/go-cmp/cmp/report.go
vendor/github.com/google/go-cmp/cmp/report_compare.go
vendor/github.com/google/go-cmp/cmp/report_references.go
vendor/github.com/google/go-cmp/cmp/report_reflect.go
vendor/github.com/google/go-cmp/cmp/report_slices.go
vendor/github.com/google/go-cmp/cmp/report_text.go
vendor/github.com/google/go-cmp/cmp/report_value.go
vendor/modules.txt

Every time we bump the Go version, the test with the expected JSON body
changes as new ciphersuites have been added or removed. Using `cmp.Diff`
makes it easier to see what the change was.

add google/go-cmp for diffing to tests

---

static/about.html
templates/index.html

I've no longer been accepting new subscriptions and long ago cancel the
existing ones. Not enough time to manage the customer relationships.
So, we remove the references to it. Maybe some day in the future, but
not now.

remove language about subscriptions

---

allow.go
allow_test.go
conn.go
howsmyssl.go
index_test.go

We use atomic.Pointer instead of the homegrown `allowMapsAtomic` type
that was made to avoid type conversions in various places.
Similarly, a `handshakeCounted` becomes an atomic.Bool instead of a
`int32` that has CompareAndSwapInt32 called on it.
Nice lil improvements.
handshakeCounted becomes an atomic.Bool

use atomic generics

---

conn.go

This got lost in an upgrade of crypto/tls but it could be handy for
testing future upgrades.

mark tls errors in conn again

---

tls_test.go

cmp is already in place, so we use it.

ditch the last use of reflect in the tests

---

.github/dependabot.yml

This is an attempt to get dependabot to group all the otel version bumps
into a single PR. I believe I've read the docs correctly but we may need
to wait a few weeks to see if it worked.

attempt to make dependabot group otel bumps

---

allow.go
howsmyssl.go
tls_test.go

Updated the code base to a more modern style with automated tooling.
Ran
```
$ go install golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@v0.18.1
$ modernize -fix .
$ modernize -fix ./gendevcerts ./gzip
```
We're ignoring the tls110 package for now since it's a fork.

modernize Go code automatically with `modernize`
