jmhodges/howsmyssl

howsmyssl.go
Some trivial changes for debugging.
=> add some referrer info

.travis.yml
This should be a nice speed-up to travis.
=> add apt caching to travis build

.travis.yml, travis_docker_push.sh
Require the docker service in travis and use the new docker push bash script (but only on green master builds).
=> fix docker pushes

.travis.yml, travis_docker_push.sh
Travis CI had to flip on a feature for this repo and have me add `edge: true` to the config.
Meanwhile, move the export to prevent prompts I've not seen, yet, and add some logging on skip.
=> fix gcloud cache

.travis.yml
"1.6" doesn't do the thing you'd think.
=> bump travis to Go 1.6.2

howsmyssl.go
This makes some kinds of debugging easier.
=> publish uptime and start time metrics

vendor/github.com/dgryski/go-topk/LICENSE, vendor/github.com/dgryski/go-topk/demo/main.go, vendor/github.com/dgryski/go-topk/topk.go
Only passed CI because TravisCI ran `go get`. Fixing that in another branch.
=> add missing topk dependency

Dockerfile
This adds the origins and Google Logging service account configs. It also uses the production name for the allowance check log.
=> add and change config file paths to Dockerfile

howsmyssl.go, tls/handshake_server.go
=> reenable Beast mitigation detection

all_suites.go, client_info.go, templates/index.html
=> make TLS 1.3 okay

all_suites.go
Please consider this change as a fix for jmhodges/howsmyssl#134
=> jmhodges/howsmyssl#134: add PSK ciphers from TLS 1.3 draft

howsmyssl.go
The best way to do things since I only have unstructured log searches right now.
=> quick and dirty User-Agent logging

all_suites.go
=> add another CHACHA20_POLY1305 cipher suites

.travis.yml, Dockerfile
Not including the crypto/tls (or handy net/http) changes.
=> bump to Go 1.8.0

allow.go, howsmyssl.go
=> flush Google log client on shutdown

allow.go, allow_test.go, howsmyssl.go
This new config file is fed by the subscription service and allows us to more
easily handle cancellation and other issues.
We check the exact domain allowlist, if the given domain in there, we return good.
We check the allowlist that has domains that have their subdomains (but not necessarily that domain) allowed, and if the given domain is in there, we return good.
We check the blocklists, and if the given domain is in there or if the given domain is a subdomain of a domain that's in there, we we return bad.
Else, we return good.
This lets us handle domains that flip flop between subscribed and not subscribed easily while also allowing for holes to be punched in wildcard blocks by subscriptions and for blocks to happen ahead of a subscription.
=> use allowlists instead of the origins file

static/api.html
=> improve language around API use

.github/workflows/go.yml
GitHub seems to require us to include some workflows in master before allowing us to use the UI in other branches.
So a quick port of just the test code. Still needs work to do the gcloud pushes.
=> initial GitHub Action attempt

howsmyssl.go
This reverts commit d7f5f7a9052076cc8b1e5cb8d8d7133aa9946e39.
=> Revert "remove port stripping hack from our handlers (#527)"

howsmyssl.go, index_test.go
This patch removes the use of `http.Hijacker` to pass around the extra
TLS client information and replaces it with `http.Server.ConnContext`.
In order to get all of the information howsmyssl needed on the TLS
client connected to it, it needed to get access to the TLS connection
for the incoming HTTP request. And howmyssl needed a fork of
`crypto/tls` to do gather all the information it needs from the TLS
client.
This, if I remember correctly, predated the existence of the
`http.Request.TLS` field, but even that field was insufficient. It's
only filled when the the `net.Listener` the `http.Server` is on is
returns exactly a `crypto/tls.Conn`, and our fork of `crypto/tls` means
that isn't ever true.
But, in the meantime, a new feature was added to `http.Server`: the
`ConnContext`. By using …
=> replace use of Hijack with ConnContext

howsmyssl.go
This reverts commit 3193e697ba4ad3ccb482e1c2f0526594bbf173ed.
=> Revert "Revert "remove port stripping hack from our handlers (#527)" (#531)"

howsmyssl.go
This ensures we add the Strict-Transport-Security header and
`Connection: close` to all HTTPS requests
Previously, these weren't set on the static file HTTP responses but both
are needed.
The `Connection: close` is needed to prevent clients from reusing TLS
connections, requiring our server to keep the memory-heavy version of
`tls.Conn` we've forked. Connection reuse also increases the chance a
client tries to perform TLS renegotiation or resumption and break our
vuln detection. I suspect this latter reason isn't a genuine problem (or
is and this only makes it less likely), but it's been a while since I
thought hard about the patch I made to `crypto/tls`.
Strict-Transport-Security should just always be set on HTTPS requests.
Fixes #525
Fixes #526
=> move common headers to tlsMux

howsmyssl.go
We forgot a comment in #535 and forgot to mention that #535 fixed #524.
Fixes #524
=> clean up leftover comment

howsmyssl.go
Now that the Hijack is gone, we pick another name for the core handling
func.
And while we're here, we comment about logHandler being replacable.
Updates #530
Updates #537
=> rename hijackHandle and comment logHandler

howsmyssl.go
Now that #529 has shipped and we've removed out uses of the `Hijack`, we
can more easily apply things like compression to our API and index
handlers using standard HTTP handler tools.
This includes a lousy hack to avoid compressing binary files by looking
for `/img/` in the HTTP request path. Possibly would be better to apply
GZIPHandler to each handler individually and then filter on the static
one using the file path given.
Fixes #192
=> gzip HTTP responses including the JSON API

howsmyssl.go
The GRPC does say not to use this. They also go on to say we're making
the wrong assumption that our configuration will be wrong more than
we'll have connectivity issues we could ignore.
The former is fine, but I suspect the latter is liekly not for us.
The docs describe how to use `ClientConn.GetState` and `Connect` to
reproduce this behavior, but the `logging` client doesn't immediately
give us access to the `ClientConn`. It does, however, have a higher
level `Ping` method that is not just a connectivity check but a
permissions check, as well. Totally fine and perhaps even better than
what was there.
=> remove use of grpc.WithBlock in Cloud Logging
